# Generated by Django 4.2.23 on 2025-09-08 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMCore', '0002_remove_address_state_alter_address_city'),
        ('TMItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMItem.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMItem.cst'),
        ),
        migrations.AlterField(
            model_name='item',
            name='onu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMItem.onu'),
        ),
        migrations.AlterField(
            model_name='item',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMItem.origin'),
        ),
        migrations.AlterField(
            model_name='item',
            name='risk_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMItem.riskclassification'),
        ),
        migrations.AlterField(
            model_name='item',
            name='risk_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMItem.risknumber'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMCore.unitmeasurement'),
        ),
    ]
