# Generated by Django 4.2.23 on 2025-09-08 19:58

import TMSale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[TMSale.models.validate_cpf], verbose_name='CPF')),
                ('alias', models.CharField(max_length=50, null=True, unique=True, verbose_name='Apelido')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['name'],
            },
        ),
    ]
