# Generated by Django 4.2.23 on 2025-10-08 20:46

import TMSale.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('TMCore', '0003_naturalperson_owner_company_naturalperson_user_and_more'),
        ('TMSale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TMCore.person')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[TMSale.models.validate_cnpj], verbose_name='CNPJ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de abertura')),
                ('tax_regime', models.CharField(blank=True, max_length=50, null=True, verbose_name='Regime tributário')),
                ('legal_nature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Natureza jurídica')),
                ('end_consumer', models.BooleanField(default=False, verbose_name='Consumidor final')),
                ('subject_protest', models.BooleanField(default=False, verbose_name='Sujeito a protesto')),
                ('logo', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='client_logos/', variations={'thumbnail': {'height': 200, 'width': 200}}, verbose_name='Logo')),
                ('isic', models.ManyToManyField(blank=True, to='TMCore.isic', verbose_name='CNAE')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
            bases=('TMCore.person',),
        ),
    ]
