# Generated by Django 4.2.23 on 2025-09-08 19:57

import TMCore.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('street', models.CharField(max_length=100, verbose_name='Rua')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['street', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('complement', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tipo de Endereço',
                'verbose_name_plural': 'Tipos de Endereço',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('complement', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor')),
                ('idd_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='DDI')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('complement', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor')),
                ('symbol_before_value', models.CharField(blank=True, max_length=10, null=True, verbose_name='Simbolo')),
                ('code_Web_service_BCB_sale', models.IntegerField(blank=True, null=True, verbose_name='Código BCB - venda')),
                ('code_Web_service_BCB_buy', models.IntegerField(blank=True, null=True, verbose_name='Código BCB - compra')),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ISIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('complement', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'CNAE',
                'verbose_name_plural': 'CNAEs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('alias', models.CharField(max_length=50, unique=True, verbose_name='Nome curto')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('home_directory', models.CharField(blank=True, max_length=255, null=True, verbose_name='Diretório base')),
                ('address', models.ManyToManyField(blank=True, to='TMCore.address', verbose_name='Endereço')),
                ('address_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TMCore.addresstype', verbose_name='Tipo de Endereço')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('complement', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tipo de Telefone',
                'verbose_name_plural': 'Tipos de Telefone',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('complement', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Unidade Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TMCore.person')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[TMCore.models.validate_cnpj], verbose_name='CNPJ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de abertura')),
                ('tax_regime', models.CharField(blank=True, max_length=50, null=True, verbose_name='Regime tributário')),
                ('legal_nature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Natureza jurídica')),
                ('end_consumer', models.BooleanField(default=False, verbose_name='Consumidor final')),
                ('subject_protest', models.BooleanField(default=False, verbose_name='Sujeito a protesto')),
                ('logo', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='company_logos/', variations={'thumbnail': {'height': 200, 'width': 200}}, verbose_name='Logo')),
                ('isic', models.ManyToManyField(blank=True, to='TMCore.isic', verbose_name='CNAE')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
            bases=('TMCore.person',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('complement', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor')),
                ('abbreviation', models.CharField(max_length=2, unique=True, verbose_name='Sigla')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TMCore.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='phone_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TMCore.phonetype', verbose_name='Tipo de Telefone'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TMCore.currency', verbose_name='Moeda'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('complement', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor')),
                ('ddd_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='DDD')),
                ('ibge_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='IBGE')),
                ('start_postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP Inicial')),
                ('end_postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP Final')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='População')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TMCore.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TMCore.person')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('photo', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='natural_person_photos/', variations={'thumbnail': {'height': 200, 'width': 200}}, verbose_name='Foto')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do pai')),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da mãe')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indefinido')], max_length=10, null=True, verbose_name='Sexo')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade')),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado civil')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('rg', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RG')),
                ('issuing_agency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Órgão emissor')),
                ('voter_registration', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Título de eleitor')),
                ('reservist_certificate', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Certificado de reservista')),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
                'indexes': [models.Index(fields=['cpf'], name='TMCore_natu_cpf_244325_idx'), models.Index(fields=['rg'], name='TMCore_natu_rg_d8236e_idx'), models.Index(fields=['voter_registration'], name='TMCore_natu_voter_r_2732a7_idx'), models.Index(fields=['reservist_certificate'], name='TMCore_natu_reservi_d3d576_idx')],
                'unique_together': {('cpf', 'rg', 'voter_registration', 'reservist_certificate')},
            },
            bases=('TMCore.person',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('start_datetime', models.DateTimeField(verbose_name='Início')),
                ('end_datetime', models.DateTimeField(verbose_name='Fim')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('all_day', models.BooleanField(default=False, verbose_name='Dia inteiro')),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to='TMCore.person', verbose_name='Participantes')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TMCore.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('is_work_day', models.BooleanField(default=True, verbose_name='Dia útil')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TMCore.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Calendário',
                'verbose_name_plural': 'Calendários',
                'ordering': ['date'],
            },
        ),
    ]
