# Generated by Django 4.2.23 on 2025-09-30 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TMCore', '0002_remove_address_state_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalperson',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMCore.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data alteração')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='Dia da semana')),
                ('open_time', models.TimeField(verbose_name='Hora de abertura')),
                ('close_time', models.TimeField(verbose_name='Hora de fechamento')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TMCore.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'ordering': ['company', 'day_of_week'],
            },
        ),
    ]
